namespace Lizzo.PV.Legion
{
    public enum RetroVfxKind
    {
        None = -1,
        CommanderMuzzle = 0,
        HealPulse = 4,
        BuffPulse = 5,
        PlayerDamaged = 8,
        EnemyDeath = 9,
        ShieldOrcCrack = 11,
        ShieldOrcDeath = 12,
        RedChargerWarning = 13,
        RedChargerCharge = 14,
        RedChargerDeath = 15,
        BossWarning = 16,
        BossAttackImpact = 17,
        BossDeath = 18,
        SynergyActivate = 19,
        GuardShockwave = 20,
        GuardRadialShield = 21,
        LevelUp = 23,
        CardSelect = 24,
        ResultClear = 25,
        XpAbsorb = 26,
        CompanionRecruit = 27,
        CompanionPromotion = 28,
        PromotionShoutActivate = 29,
        SynergyReady = 30,
        SynergyComplete = 31,
        RapidCrossbowCast = 32,
        PiercingSpearCast = 34,
        BlastStaffCast = 36,
        BlastStaffExplosion = 37,
        BossSpawn = 38,
    }
}
